project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/[0-9]*.qmd"
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600

execute:
  freeze: auto

website:
  page-navigation: true
  # Edit
  title: "Parameterized Reporting with Quarto: R-Ladies Abuja"
  # Edit
  description: "Homepage for the 2024 R-Ladies Abuja Parameterized Reports with Quarto Workshop"
  # Edit
  site-url: "https://jadeyryan.quarto.pub/rladies-abuja-quarto-params/"
  # Edit
  favicon: "images/jr-logo-circle.webp"

  # Edit
  repo-url: https://github.com/jadeynryan/parameterized-quarto-workshop
  repo-actions: [source, edit, issue]

  page-footer:
    # Edit
    left: "&copy; 2024 Jadey Ryan"
    center: "Website built with ❤︎️ and [Quarto](https://quarto.org/)."
    # Please don't remove this acknowledgement.
    right: "[Workshop template](https://github.com/jadeynryan/workshop-template) from [Jadey Ryan](https://jadeyryan.com)."

  sidebar:
    # Edit
    logo: "images/jr-logo-quarto.webp"
    # Edit
    logo-alt: "Two hex stickers side by side with a heart joining them in the middle. Left sticker is Jadey's cat logo. Right sticker is the Quarto logo."
    pinned: true
    align: center
    style: docked
    tools:
      - icon: github
        # Edit
        href: https://github.com/jadeynryan/parameterized-quarto-workshop
        text: GitHub
    contents:
    # Edit as needed
     - href: index.qmd
       text: Home
     - href: prework.qmd
       text: Pre-work
     - href: materials.qmd
       text: Materials
     - href: license.qmd
       text: License

format:
  html:
    # Edit if you want to use another Bootswatch theme
    theme: [flatly, theme.scss]
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    code-copy: true
    code-overflow: scroll
    highlight-style: a11y

# lightbox extension
# https://github.com/quarto-ext/lightbox
lightbox:
  desc-position: right  # position of description
  # match: auto # give all images lightbox treatment
  effect: zoom # how lightbox opens/closes
  loop: false # doesn't loop to first image in gallery
